// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUh_akt0HpVqPwicWqD9mWYv_zuM61KU',
    appId: '1:332964832866:web:6b0ea62cfbd6e666a9533b',
    messagingSenderId: '332964832866',
    projectId: 'cobalto-3697f',
    authDomain: 'cobalto-3697f.firebaseapp.com',
    storageBucket: 'cobalto-3697f.firebasestorage.app',
    measurementId: 'G-6YGNFVNXTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-oqR4MrYwn2e3TR46F8MQso832BegQA',
    appId: '1:332964832866:android:9e06fe684e7e5b88a9533b',
    messagingSenderId: '332964832866',
    projectId: 'cobalto-3697f',
    storageBucket: 'cobalto-3697f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1IlXxP38ozJex9S7ROm9SZ7NF_yIr4M',
    appId: '1:332964832866:ios:bc3a2e0f834ea35ea9533b',
    messagingSenderId: '332964832866',
    projectId: 'cobalto-3697f',
    storageBucket: 'cobalto-3697f.firebasestorage.app',
    iosBundleId: 'com.example.apkRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1IlXxP38ozJex9S7ROm9SZ7NF_yIr4M',
    appId: '1:332964832866:ios:bc3a2e0f834ea35ea9533b',
    messagingSenderId: '332964832866',
    projectId: 'cobalto-3697f',
    storageBucket: 'cobalto-3697f.firebasestorage.app',
    iosBundleId: 'com.example.apkRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUh_akt0HpVqPwicWqD9mWYv_zuM61KU',
    appId: '1:332964832866:web:7392850be4f9aa48a9533b',
    messagingSenderId: '332964832866',
    projectId: 'cobalto-3697f',
    authDomain: 'cobalto-3697f.firebaseapp.com',
    storageBucket: 'cobalto-3697f.firebasestorage.app',
    measurementId: 'G-008BJ464EK',
  );
}
